/* Fleet admin.
   No framework, same rule as the workbench: a product whose claim is that it
   touches no network must not fetch a UI library from one. The reference was a
   React/Tailwind sidebar; what was worth keeping is its shape - a quiet rail,
   one accent, data allowed to be the loudest thing on screen. */

const $ = s => document.querySelector(s);
const esc = s => String(s ?? "").replace(/[&<>"]/g,
  c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));

let TOKEN = sessionStorage.getItem("adm") || "";
let DAYS = 30, VIEW = "fleet", PERSON = null, DATA = null;

const int = n => (n || 0).toLocaleString();
const tok = n => n >= 1e6 ? (n / 1e6).toFixed(2) + "M"
               : n >= 1e3 ? (n / 1e3).toFixed(1) + "k" : String(n || 0);
const money = n => (n || 0).toFixed(2);

async function api(path){
  const r = await fetch(path, { headers: { "X-Admin-Token": TOKEN } });
  if(r.status === 401){ signedOut(); throw new Error("signed out"); }
  return r.json();
}

/* ---------- sign in ---------- */
function signedOut(){
  TOKEN = ""; sessionStorage.removeItem("adm");
  $("#shell").hidden = true; $("#gate").hidden = false;
}

$("#loginform").onsubmit = async e => {
  e.preventDefault();
  const btn = $("#signin"), err = $("#loginerr");
  btn.disabled = true; err.hidden = true;
  try{
    const r = await (await fetch("/api/admin/login", {
      method: "POST", headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ email: $("#email").value, password: $("#password").value }),
    })).json();
    if(!r.ok){ err.textContent = r.error || "Could not sign in"; err.hidden = false; return; }
    TOKEN = r.token; sessionStorage.setItem("adm", TOKEN);
    $("#whoami").textContent = r.email;
    await enter();
  }catch(_){ err.textContent = "Server unreachable"; err.hidden = false; }
  finally{ btn.disabled = false; }
};

$("#signout").onclick = async () => {
  try{ await fetch("/api/admin/logout", { method: "POST",
        headers: { "X-Admin-Token": TOKEN } }); }catch(_){}
  signedOut();
};

async function enter(){
  $("#gate").hidden = true; $("#shell").hidden = false;
  renderRange();
  await load();
}

/* ---------- chrome ---------- */
function renderRange(){
  $("#range").innerHTML = [1, 7, 30, 90].map(n =>
    `<button data-d="${n}" class="${n === DAYS ? "on" : ""}">${
      n === 1 ? "today" : n + "d"}</button>`).join("");
  $("#range").querySelectorAll("button").forEach(b => {
    b.onclick = () => { DAYS = +b.dataset.d; renderRange(); load(); };
  });
}

document.querySelectorAll(".nav[data-view]").forEach(b => {
  b.onclick = () => { VIEW = b.dataset.view; PERSON = null; paint(); };
});

function markNav(){
  document.querySelectorAll(".nav[data-view]").forEach(b =>
    b.classList.toggle("on", !PERSON && b.dataset.view === VIEW));
  document.querySelectorAll(".nav[data-pc]").forEach(b =>
    b.classList.toggle("on", b.dataset.pc === PERSON));
}

async function load(){
  DATA = await api(`/api/admin/overview?days=${DAYS}`);
  $("#orgsub").textContent = `${DATA.capacity.machines_seen} workbenches`;
  renderPeople();
  paint();
}

function renderPeople(){
  const rows = DATA.machines;
  const top = Math.max(1, ...rows.map(r => r.seconds));
  $("#pcount").textContent = rows.length;
  $("#people").innerHTML = rows.map(r => {
    const cls = r.calls === 0 ? "idle" : r.seconds > top * 0.5 ? "heavy" : "";
    return `<button class="nav" data-pc="${esc(r.key)}">
      <span class="pdot ${cls}"></span>
      <span>${esc(r.user || r.key)}</span>
      <span class="tail">${r.calls ? tok(r.prompt_tokens + r.output_tokens) : "—"}</span>
    </button>`;
  }).join("");
  $("#people").querySelectorAll("[data-pc]").forEach(b => {
    b.onclick = () => { PERSON = b.dataset.pc; paint(); };
  });
}

/* ---------- views ---------- */
function paint(){
  markNav();
  const v = $("#view");
  const crumb = PERSON ? (DATA.machines.find(m => m.key === PERSON)?.user || PERSON)
    : { fleet: "Fleet", models: "Models", matrix: "Token matrix",
        power: "Electricity" }[VIEW];
  $("#crumb-a").textContent = crumb;
  const banner = DATA.demo_rows
    ? `<div class="demo">simulated fleet — generated by tools/make_fleet_demo.py</div>` : "";
  if(PERSON) return void person(v, banner);
  if(VIEW === "models") return void models(v, banner);
  if(VIEW === "matrix") return void matrix(v);
  if(VIEW === "power")  return void power(v, banner);
  fleet(v, banner);
}

function bars(list, key = "seconds", label = h => h.hour + ":00"){
  const top = Math.max(1, ...list.map(x => x[key]));
  return `<div class="spark">${list.map(x =>
    `<i style="height:${Math.max(2, x[key] / top * 100)}%"
        title="${esc(label(x))} · ${x.calls} calls"></i>`).join("")}</div>`;
}

function fleet(v, banner){
  const d = DATA, c = d.capacity, t = d.total;
  const util = Math.round((c.utilisation || 0) * 100);
  const idle = d.machines.filter(m => m.calls === 0);
  const topTok = Math.max(1, ...d.machines.map(m => m.prompt_tokens + m.output_tokens));
  v.innerHTML = `${banner}
  <div class="cards">
    <div class="card"><div class="k">workbenches</div><div class="v">${c.machines_seen}</div>
      <div class="n">${idle.length} never used</div></div>
    <div class="card accent"><div class="k">node utilisation</div><div class="v">${util}%</div>
      <div class="n">${(c.engine_seconds / 3600).toFixed(1)}h engine over
        ${(c.window_hours || 0).toFixed(0)}h</div></div>
    <div class="card"><div class="k">requests</div><div class="v">${int(t.calls)}</div>
      <div class="n">${int(t.tokens_per_call)} tokens each</div></div>
    <div class="card"><div class="k">tokens</div><div class="v">${tok(t.tokens)}</div>
      <div class="n">${tok(t.prompt_tokens)} in · ${tok(t.output_tokens)} out</div></div>
    <div class="card ok"><div class="k">electricity</div>
      <div class="v">${money(d.energy.bill)}</div>
      <div class="n">${d.energy.kwh} kWh at ${d.energy.tariff}/kWh</div></div>
  </div>

  <h2 class="sec">When the node is busy</h2>
  <p class="why">Engine-seconds by hour of day. This decides whether one node is
    enough — a flat line is headroom, a wall at 10:00 means engineers are
    queueing behind each other.</p>
  ${bars(c.by_hour)}

  <h2 class="sec">Every workbench</h2>
  <p class="why">One deployment per engineer's PC, so a row is a person's load on
    the shared node. The bottom of this table matters as much as the top: a PC at
    zero is a rollout nobody is using.
    ${idle.length ? "Never used: " + idle.map(m => esc(m.key)).join(", ") + "." : ""}</p>
  <table><thead><tr>
    <th>engineer</th><th>machine</th><th>role</th>
    <th class="num">calls</th><th class="num">tokens</th>
    <th class="num">engine h</th><th class="num">power</th></tr></thead>
  <tbody>${d.machines.map(m => {
    const tk = m.prompt_tokens + m.output_tokens;
    return `<tr class="${m.calls ? "" : "dim"}">
      <td><a href="#" data-go="${esc(m.key)}">${esc(m.user || "—")}</a>
        <div class="bar"><i style="width:${Math.round(tk / topTok * 100)}%"></i></div></td>
      <td>${esc(m.key)}</td><td>${esc(m.role || "—")}</td>
      <td class="num">${int(m.calls)}</td><td class="num">${tok(tk)}</td>
      <td class="num">${m.engine_hours}</td><td class="num">${money(m.power_cost)}</td>
    </tr>`;
  }).join("")}</tbody></table>`;
  v.querySelectorAll("[data-go]").forEach(a => {
    a.onclick = e => { e.preventDefault(); PERSON = a.dataset.go; paint(); };
  });
}

async function person(v, banner){
  v.innerHTML = `<p class="note">Loading…</p>`;
  const p = await api(`/api/admin/person/${encodeURIComponent(PERSON)}?days=${DAYS}`);
  if(!p.found){ v.innerHTML = `${banner}<div class="empty">
    <b>${esc(PERSON)}</b> has not made a single request in this window.
    The workbench is installed and has never been opened.</div>`; return; }
  const t = p.total, ln = DATA.lane_notes || {};
  v.innerHTML = `${banner}
  <div class="cards">
    <div class="card"><div class="k">engineer</div>
      <div class="v" style="font-size:19px">${esc(p.user)}</div>
      <div class="n">${esc(p.role || "")} · ${esc(p.machine)}</div></div>
    <div class="card"><div class="k">requests</div><div class="v">${int(t.calls)}</div>
      <div class="n">${int(Math.round(t.tokens / Math.max(1, t.calls)))} tokens each</div></div>
    <div class="card"><div class="k">tokens</div><div class="v">${tok(t.tokens)}</div>
      <div class="n">${tok(t.prompt_tokens)} in · ${tok(t.output_tokens)} out</div></div>
    <div class="card accent"><div class="k">engine time</div>
      <div class="v">${p.engine_hours}h</div>
      <div class="n">share of the node they occupied</div></div>
    <div class="card ok"><div class="k">their electricity</div>
      <div class="v">${money(p.power_cost)}</div>
      <div class="n">${p.energy_kwh} kWh</div></div>
  </div>

  <div class="split">
    <div>
      <h2 class="sec">What they use it for</h2>
      <p class="why">Lanes, not features. A person heavy on <b>reason</b> is asking
        judgement questions; heavy on <b>embed</b> means they keep loading new
        documents.</p>
      <table><thead><tr><th>lane</th><th class="num">calls</th>
        <th class="num">tokens</th></tr></thead><tbody>
        ${p.lanes.map(l => `<tr><td><b>${esc(l.key)}</b>
          <div class="n" style="color:var(--dim2);font-size:11.5px">
            ${esc(ln[l.key] || "")}</div></td>
          <td class="num">${int(l.calls)}</td>
          <td class="num">${tok(l.prompt_tokens + l.output_tokens)}</td></tr>`).join("")}
      </tbody></table>
    </div>
    <div>
      <h2 class="sec">Models they reached</h2>
      <table><thead><tr><th>model</th><th class="num">calls</th>
        <th class="num">tokens</th></tr></thead><tbody>
        ${p.models.map(m => `<tr><td>${esc(m.key)}</td>
          <td class="num">${int(m.calls)}</td>
          <td class="num">${tok(m.prompt_tokens + m.output_tokens)}</td></tr>`).join("")}
      </tbody></table>
      <h2 class="sec">Hours they work</h2>
      ${bars(p.hourly)}
    </div>
  </div>

  <h2 class="sec">Daily</h2>
  ${bars(p.daily.map(d => ({ ...d, hour: d.key })), "calls", d => d.key)}`;
}

let MODEL = null, RAM = 64, CTX = 8;

function models(v, banner){
  const cat = DATA.catalogue || {}, used = DATA.models;
  if(!MODEL) MODEL = used[0]?.key || Object.keys(cat)[0];
  const row = used.find(m => m.key === MODEL) || { calls: 0, prompt_tokens: 0,
    output_tokens: 0, seconds: 0, cost_usd: 0 };
  const info = cat[MODEL] || { kind: "—", why: "Not in the catalogue." };
  const tot = DATA.total.tokens || 1;
  const tk = row.prompt_tokens + row.output_tokens;

  v.innerHTML = `${banner}
  <p class="note">Every model the fleet ran, what it is for, and what it is doing
    to the node. A name on its own tells nobody anything — these screens are read
    by people who did not choose the models.</p>
  <div class="picker">${Object.keys(cat).map(m => {
    const u = used.find(x => x.key === m);
    return `<button data-m="${esc(m)}" class="${m === MODEL ? "on" : ""}">
      ${esc(m)} ${u ? "" : '<span class="tag quiet">unused</span>'}</button>`;
  }).join("")}</div>

  <div class="split">
    <div class="panel">
      <h2 class="sec" style="margin-top:0">${esc(MODEL)}</h2>
      <p class="why"><span class="tag ${info.hosted ? "hosted" : "local"}">
        ${info.hosted ? "hosted" : "on-premise"}</span>
        &nbsp;<b>${esc(info.kind)}</b></p>
      <p class="why">${esc(info.why)}</p>
      <div class="kv"><span>Requests</span><b>${int(row.calls)}</b></div>
      <div class="kv"><span>Tokens</span><b>${tok(tk)}</b></div>
      <div class="kv"><span>Share of all tokens</span>
        <b>${Math.round(tk / tot * 100)}%</b></div>
      <div class="kv"><span>Engine time</span>
        <b>${(row.seconds / 3600).toFixed(2)} h</b></div>
      <div class="kv"><span>Cost</span><b>${info.hosted
        ? money(row.cost_usd) + " billed"
        : money(row.cost_usd) + " of node time"}</b></div>
      ${info.price ? `<div class="kv"><span>List price</span>
        <b>${info.price.input} in / ${info.price.output} out per 1M</b></div>` : ""}
    </div>
    <div>
      <h2 class="sec" style="margin-top:0">All models, by load</h2>
      <p class="why">A router near the top of this table means a large model is
        doing a small model's work — the most common way an on-premise node
        runs out of room.</p>
      <table><thead><tr><th>model</th><th class="num">calls</th>
        <th class="num">tokens</th><th class="num">engine h</th></tr></thead>
      <tbody>${used.map(m => {
        const t2 = m.prompt_tokens + m.output_tokens;
        return `<tr><td>${esc(m.key)}
          <div class="bar"><i style="width:${Math.round(t2 / tot * 100)}%"></i></div>
          </td><td class="num">${int(m.calls)}</td>
          <td class="num">${tok(t2)}</td>
          <td class="num">${(m.seconds / 3600).toFixed(2)}</td></tr>`;
      }).join("")}</tbody></table>
    </div>
  </div>`;
  v.querySelectorAll("[data-m]").forEach(b => {
    b.onclick = () => { MODEL = b.dataset.m; paint(); };
  });
}

async function matrix(v){
  v.innerHTML = `<p class="note">Loading…</p>`;
  const m = await api(`/api/admin/matrix?ram_gb=${RAM}&context_k=${CTX}`);
  const RAMS = [16, 32, 64, 128, 256, 512];
  const CTXS = [4, 8, 16, 32, 128];
  v.innerHTML = `
  <p class="note">How many engineers one node holds at once. Weights are what the
    model occupies before anybody asks it anything; the KV cache is what each
    open conversation holds on top, and it is the part that actually runs a
    server out of memory. ${m.reserved_gb} GB is left for the OS and the server
    process rather than pretending all of it is available.</p>
  <div class="picker">${RAMS.map(r =>
    `<button data-ram="${r}" class="${r === RAM ? "on" : ""}">${r} GB</button>`).join("")}</div>
  <div class="picker">${CTXS.map(c =>
    `<button data-ctx="${c}" class="${c === CTX ? "on" : ""}">${c}k context</button>`).join("")}</div>

  <div class="cards">
    <div class="card"><div class="k">server RAM</div><div class="v">${m.ram_gb} GB</div>
      <div class="n">${m.usable_gb} GB usable after reserve</div></div>
    <div class="card"><div class="k">context per seat</div>
      <div class="v">${m.context_k}k</div>
      <div class="n">tokens held open per conversation</div></div>
  </div>

  <h2 class="sec">Concurrent engineers per model</h2>
  <table><thead><tr><th>model</th><th class="num">weights</th>
    <th class="num">KV per seat</th><th class="num">concurrent</th>
    <th>headroom</th></tr></thead><tbody>
    ${m.rows.map(r => {
      const top = Math.max(1, ...m.rows.map(x => x.concurrent));
      const pct = Math.round(r.concurrent / top * 100);
      const cls = !r.fits ? "bad" : r.concurrent < 8 ? "warn" : "ok";
      return `<tr class="${r.fits ? "" : "dim"}">
        <td>${esc(r.model)}</td>
        <td class="num">${r.weights_gb} GB</td>
        <td class="num">${r.kv_gb} GB</td>
        <td class="num"><b>${r.fits ? r.concurrent : "does not fit"}</b></td>
        <td><div class="bar"><i class="${cls}" style="width:${pct}%"></i></div></td>
      </tr>`;
    }).join("")}</tbody></table>
  <p class="why" style="margin-top:14px">Read the row you plan to serve. If the
    concurrent figure is below your headcount at 10:00, one node is not enough —
    and that is a purchase decision, not a tuning one.</p>`;
  v.querySelectorAll("[data-ram]").forEach(b => {
    b.onclick = () => { RAM = +b.dataset.ram; paint(); };
  });
  v.querySelectorAll("[data-ctx]").forEach(b => {
    b.onclick = () => { CTX = +b.dataset.ctx; paint(); };
  });
}

function power(v, banner){
  const d = DATA, e = d.energy, o = d.onprem || {};
  const rows = d.machines.filter(m => m.calls > 0);
  const top = Math.max(1, ...rows.map(m => m.power_cost));
  const perDay = e.bill / Math.max(1, d.days);
  v.innerHTML = `${banner}
  <p class="note">There is no vendor invoice for a model the plant hosts, so the
    running cost is electricity plus the node written off over its life. These
    are four numbers in <b>models.yaml</b> that the person who signed for the GPU
    can argue with — change them and every figure here moves.</p>

  <div class="cards">
    <div class="card ok"><div class="k">bill for ${d.days} days</div>
      <div class="v">${money(e.bill)}</div>
      <div class="n">${e.kwh} kWh at ${e.tariff}/kWh</div></div>
    <div class="card"><div class="k">per day</div><div class="v">${money(perDay)}</div>
      <div class="n">at the current load</div></div>
    <div class="card"><div class="k">per million tokens</div>
      <div class="v">${money(e.per_million_tokens)}</div>
      <div class="n">the only per-token price that is real here</div></div>
    <div class="card accent"><div class="k">node time</div>
      <div class="v">${money(d.onprem_rate_hour)}</div>
      <div class="n">per engine-hour, capex + power</div></div>
  </div>

  <div class="split">
    <div>
      <h2 class="sec">Where the power goes</h2>
      <p class="why">Attributed by engine seconds, because that is what actually
        draws current. Tokens are a proxy; seconds are the meter.</p>
      <table><thead><tr><th>engineer</th><th class="num">engine h</th>
        <th class="num">kWh</th><th class="num">cost</th></tr></thead><tbody>
        ${rows.map(m => `<tr><td>${esc(m.user || m.key)}
          <div class="bar"><i class="ok" style="width:${
            Math.round(m.power_cost / top * 100)}%"></i></div></td>
          <td class="num">${m.engine_hours}</td>
          <td class="num">${m.energy_kwh}</td>
          <td class="num">${money(m.power_cost)}</td></tr>`).join("")}
      </tbody></table>
    </div>
    <div class="panel">
      <h2 class="sec" style="margin-top:0">How it is worked out</h2>
      <div class="kv"><span>Node purchase price</span><b>${int(o.node_cost)}</b></div>
      <div class="kv"><span>Written off over</span><b>${o.life_years} years</b></div>
      <div class="kv"><span>Draw under load</span><b>${o.draw_watts} W</b></div>
      <div class="kv"><span>Tariff</span><b>${o.power_per_kwh} / kWh</b></div>
      <div class="kv"><span>= cost per engine-hour</span>
        <b>${money(d.onprem_rate_hour)}</b></div>
      <p class="why" style="margin-top:14px">A hosted model would be billed per
        token instead, and both appear side by side on the fleet screen. The
        comparison is the argument: this column is the plant's own hardware, and
        nothing on it leaves the site.</p>
    </div>
  </div>`;
}

/* ---------- boot ---------- */
if(TOKEN){
  api("/api/admin/overview?days=1").then(() => enter()).catch(() => signedOut());
}
