"""
Deliverable writers - turn an answer into a real file.

PS 26117, Expected Solution (verbatim):
  "Output should be real deliverables, approval notes, PPT/Word/Excel files,
   working code, calculations with steps shown, not just chat replies."
  "...for example reading a scanned inspection report, pulling out key
   findings and drafting an approval note as a Word file."

So this module is the difference between a chatbot and the thing the PS asks
for. Everything is written locally with python-docx / openpyxl / python-pptx;
no template service, no cloud renderer.

Design note: the model does NOT write the file. The model returns structured
JSON, and Python renders it. A 2b model cannot be trusted to produce valid
OOXML, but it can fill a schema. That split also means a malformed model
response degrades into a partly-empty document instead of a crash.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any

_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = _ROOT / "data" / "deliverables"

# Documents carry a citation line so a reader can trace any claim back to the
# source file and page. Without this an "approval note" is just generated text.
CITE_NOTE = ("Generated by Sovereign Workbench from the indexed corpus. "
             "Every finding is traceable to the source listed below.")


@dataclass
class Deliverable:
    path: Path
    kind: str
    title: str
    bytes: int

    def as_dict(self) -> dict:
        return {"file": self.path.name, "path": str(self.path),
                "kind": self.kind, "title": self.title, "bytes": self.bytes}


def _stamp(name: str, ext: str) -> Path:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    safe = re.sub(r"[^A-Za-z0-9_.-]+", "_", name).strip("_")[:60] or "document"
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    return OUT_DIR / f"{safe}_{ts}.{ext}"


def _sources_block(sources: list[dict] | None) -> list[str]:
    if not sources:
        return []
    out = []
    for s in sources:
        n = s.get("n", "?")
        cite = s.get("cite") or s.get("source", "")
        out.append(f"[{n}] {cite}")
    return out


# ---------------------------------------------------------------------------
# Word
# ---------------------------------------------------------------------------


def write_docx(spec: dict, sources: list[dict] | None = None) -> Deliverable:
    """
    spec = {
      "title": str,
      "subtitle": str | None,
      "meta": {label: value},            # Ref no, date, unit ...
      "sections": [ {"heading": str,
                     "paragraphs": [str],
                     "bullets": [str],
                     "table": {"columns": [...], "rows": [[...]]}} ],
      "decision": str | None,            # highlighted box at the end
      "signoff": [str],
    }
    """
    from docx import Document
    from docx.shared import Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    title = spec.get("title") or "Document"
    d = Document()

    d.add_heading(title, 0)
    if spec.get("subtitle"):
        p = d.add_paragraph(spec["subtitle"])
        p.runs[0].italic = True

    meta = spec.get("meta") or {}
    if meta:
        line = "    ".join(f"{k}: {v}" for k, v in meta.items())
        mp = d.add_paragraph(line)
        mp.runs[0].font.size = Pt(9)
        mp.runs[0].font.color.rgb = RGBColor(0x60, 0x60, 0x60)

    for sec in spec.get("sections") or []:
        if sec.get("heading"):
            d.add_heading(str(sec["heading"]), 1)
        for para in sec.get("paragraphs") or []:
            d.add_paragraph(str(para))
        for b in sec.get("bullets") or []:
            d.add_paragraph(str(b), style="List Bullet")
        tbl = sec.get("table")
        if tbl and tbl.get("columns"):
            cols = [str(c) for c in tbl["columns"]]
            t = d.add_table(rows=1, cols=len(cols))
            t.style = "Table Grid"
            for i, c in enumerate(cols):
                cell = t.rows[0].cells[i]
                cell.text = c
                for r in cell.paragraphs[0].runs:
                    r.bold = True
            for row in tbl.get("rows") or []:
                cells = t.add_row().cells
                for i, v in enumerate(row[:len(cols)]):
                    cells[i].text = "" if v is None else str(v)

    if spec.get("decision"):
        d.add_heading("Decision", 1)
        dp = d.add_paragraph(str(spec["decision"]))
        dp.runs[0].bold = True

    for line in spec.get("signoff") or []:
        d.add_paragraph(str(line))

    srcs = _sources_block(sources)
    if srcs:
        d.add_page_break()
        d.add_heading("Sources", 1)
        note = d.add_paragraph(CITE_NOTE)
        note.runs[0].font.size = Pt(9)
        note.runs[0].italic = True
        for s in srcs:
            sp = d.add_paragraph(s, style="List Number")
            sp.runs[0].font.size = Pt(9)

    path = _stamp(title, "docx")
    d.save(path)
    return Deliverable(path, "docx", title, path.stat().st_size)


# ---------------------------------------------------------------------------
# Excel
# ---------------------------------------------------------------------------


def write_xlsx(spec: dict, sources: list[dict] | None = None) -> Deliverable:
    """
    spec = {
      "title": str,
      "sheets": [ {"name": str,
                   "columns": [...], "rows": [[...]],
                   "formulas": [{"cell": "E2", "formula": "=D2/C2"}],
                   "notes": [str]} ]
    }

    Formulas are written as real Excel formulas, not pre-computed values, so
    "calculations with steps shown" survives in the file the engineer opens.
    """
    from openpyxl import Workbook
    from openpyxl.styles import Font, Alignment, PatternFill

    title = spec.get("title") or "Workbook"
    wb = Workbook()
    wb.remove(wb.active)
    head_fill = PatternFill("solid", fgColor="EEEAE0")

    for sheet in spec.get("sheets") or [{"name": "Sheet1"}]:
        ws = wb.create_sheet(str(sheet.get("name") or "Sheet")[:31])
        cols = [str(c) for c in (sheet.get("columns") or [])]
        if cols:
            ws.append(cols)
            for c in ws[1]:
                c.font = Font(bold=True)
                c.fill = head_fill
                c.alignment = Alignment(horizontal="center")
        for row in sheet.get("rows") or []:
            ws.append(list(row))
        for f in sheet.get("formulas") or []:
            if f.get("cell") and f.get("formula"):
                ws[f["cell"]] = f["formula"]
        if cols:
            for i, c in enumerate(cols, 1):
                width = max(len(c) + 2, 12)
                ws.column_dimensions[ws.cell(1, i).column_letter].width = width
        notes = sheet.get("notes") or []
        if notes:
            ws.append([])
            for n in notes:
                ws.append([str(n)])

    if sources:
        ws = wb.create_sheet("Sources")
        ws.append(["Ref", "Source"])
        for c in ws[1]:
            c.font = Font(bold=True)
        for s in sources:
            ws.append([f"[{s.get('n','?')}]", s.get("cite") or s.get("source", "")])
        ws.column_dimensions["B"].width = 70

    path = _stamp(title, "xlsx")
    wb.save(path)
    return Deliverable(path, "xlsx", title, path.stat().st_size)


# ---------------------------------------------------------------------------
# PowerPoint
# ---------------------------------------------------------------------------


def write_pptx(spec: dict, sources: list[dict] | None = None) -> Deliverable:
    """
    spec = {
      "title": str, "subtitle": str,
      "slides": [ {"title": str, "bullets": [str], "notes": str} ]
    }
    """
    from pptx import Presentation
    from pptx.util import Pt

    title = spec.get("title") or "Presentation"
    pr = Presentation()

    s = pr.slides.add_slide(pr.slide_layouts[0])
    s.shapes.title.text = title
    if len(s.placeholders) > 1:
        s.placeholders[1].text = spec.get("subtitle") or ""

    for sl in spec.get("slides") or []:
        slide = pr.slides.add_slide(pr.slide_layouts[1])
        slide.shapes.title.text = str(sl.get("title") or "")
        bullets = [str(b) for b in (sl.get("bullets") or [])]
        if bullets:
            tf = slide.placeholders[1].text_frame
            tf.text = bullets[0]
            for b in bullets[1:]:
                para = tf.add_paragraph()
                para.text = b
                para.level = 0
        if sl.get("notes"):
            slide.notes_slide.notes_text_frame.text = str(sl["notes"])

    srcs = _sources_block(sources)
    if srcs:
        slide = pr.slides.add_slide(pr.slide_layouts[1])
        slide.shapes.title.text = "Sources"
        tf = slide.placeholders[1].text_frame
        tf.text = srcs[0]
        for s_ in srcs[1:]:
            para = tf.add_paragraph()
            para.text = s_
            para.level = 0

    path = _stamp(title, "pptx")
    pr.save(path)
    return Deliverable(path, "pptx", title, path.stat().st_size)


# ---------------------------------------------------------------------------
# model output -> spec
# ---------------------------------------------------------------------------


# A spec is only usable if it carries the payload key for its kind. Without
# this check a parser can lock onto a NESTED object (a "meta" block, say) and
# report success while the document comes out empty.
TOP_KEYS = {
    "docx": ("sections", "title", "decision"),
    "xlsx": ("sheets", "title"),
    "pptx": ("slides", "title"),
}
PAYLOAD_KEY = {"docx": "sections", "xlsx": "sheets", "pptx": "slides"}


def _try_json(raw: str) -> dict | None:
    for attempt in (raw, re.sub(r",(\s*[}\]])", r"\1", raw)):
        try:
            val = json.loads(attempt)
            return val if isinstance(val, dict) else None
        except json.JSONDecodeError:
            continue
    return None


def _candidates(text: str):
    """Every plausible JSON payload in a model reply, best first."""
    t = text.strip()
    # 1. the whole thing
    yield t
    # 2. a fenced block
    for m in re.finditer(r"```(?:json)?\s*(.*?)\s*```", t, re.S):
        yield m.group(1)
    # 3. balanced braces from each opening brace
    for start in (i for i, ch in enumerate(t) if ch == "{"):
        depth = 0
        for i, ch in enumerate(t[start:], start):
            if ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    yield t[start:i + 1]
                    break
    # 4. the model dropped the outer braces and began with a quoted key
    if re.match(r'^"[A-Za-z_]', t):
        yield "{" + t.rstrip().rstrip(",") + "}"
        yield "{" + t.rstrip().rstrip(",") + "}}"      # one unclosed nesting


def parse_spec(text: str, kind: str | None = None) -> dict | None:
    """
    Pull a usable document spec out of a model reply.

    Small models wrap JSON in prose or fences, emit trailing commas, and
    sometimes omit the outer braces entirely. Be liberal about the input but
    strict about the result: when `kind` is given, the object must contain a
    key that actually carries content for that kind, otherwise we would
    silently render an empty document.
    """
    if not text:
        return None
    wanted = TOP_KEYS.get(kind or "", ())
    fallback = None

    for raw in _candidates(text):
        val = _try_json(raw)
        if val is None:
            continue
        if not wanted:
            return val
        if PAYLOAD_KEY.get(kind) in val:        # has the real payload
            return val
        if any(w in val for w in wanted) and fallback is None:
            fallback = val                      # title-only: keep looking
    return fallback


WRITERS = {"docx": write_docx, "xlsx": write_xlsx, "pptx": write_pptx}


def build(kind: str, spec: dict, sources: list[dict] | None = None) -> Deliverable:
    if kind not in WRITERS:
        raise ValueError(f"unknown deliverable kind {kind!r}; have {sorted(WRITERS)}")
    return WRITERS[kind](spec, sources)


# JSON schemas handed to the model. Kept terse on purpose: a 2b model follows
# a short schema far more reliably than a thorough one.
SCHEMAS = {
"docx": '''{
 "title": "APPROVAL NOTE - <TAG>",
 "subtitle": "one line of context",
 "meta": {"Ref": "...", "Date": "...", "Unit": "..."},
 "sections": [
   {"heading": "Findings",
    "bullets": ["finding with the exact number and its [n] citation"]},
   {"heading": "Assessment",
    "paragraphs": ["what the finding means against the SOP"]},
   {"heading": "Measurements",
    "table": {"columns": ["Item","Measured","Required"],
              "rows": [["...","...","..."]]}}
 ],
 "decision": "the recommendation, with conditions",
 "signoff": ["Prepared by: Sovereign Workbench", "Approved by: ______"]
}''',
"xlsx": '''{
 "title": "...",
 "sheets": [
   {"name": "Readings",
    "columns": ["Item","Nominal","Measured","Loss"],
    "rows": [["...", 0, 0, 0]],
    "formulas": [{"cell": "E2", "formula": "=C2-D2"}],
    "notes": ["assumption or method note"]}
 ]
}''',
"pptx": '''{
 "title": "...",
 "subtitle": "...",
 "slides": [
   {"title": "Slide title", "bullets": ["point with [n] citation"],
    "notes": "speaker note"}
 ]
}''',
}


def list_deliverables() -> list[dict]:
    if not OUT_DIR.exists():
        return []
    out = []
    for f in sorted(OUT_DIR.iterdir(), key=lambda x: x.stat().st_mtime, reverse=True):
        if f.is_file() and f.suffix.lstrip(".") in WRITERS:
            out.append({"file": f.name, "kind": f.suffix.lstrip("."),
                        "bytes": f.stat().st_size, "mtime": f.stat().st_mtime})
    return out
