"""
Point the workbench at a folder on this machine and index what is in it.

PS 26117 asks for "a local knowledge base connector" so the assistant can
ground itself in "the organization's own manuals, SOPs and past
correspondence". Uploading files one at a time does not describe how an
engineer actually works - the manuals already sit in a folder on the server.

Nothing leaves the machine: this reads from a local path with the same ingest
pipeline the upload button uses.

Two rules that matter more than they look:

  * The folder is walked, never copied. A 400 MB manuals directory should not
    be duplicated into data/corpus to be read once.
  * Files generated by this system are skipped, as everywhere else. A folder
    that happens to contain last week's approval notes must not turn them into
    evidence.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from pathlib import Path

from ingest import pipeline

# Walking an entire home directory by accident should not be possible.
MAX_FILES = 400
MAX_BYTES = 300 * 1024 * 1024
SKIP_DIRS = {".git", "node_modules", "__pycache__", ".venv", "venv",
             "Library", "System", ".Trash", "site-packages", ".cache"}


@dataclass
class Scan:
    root: str
    found: int = 0
    supported: int = 0
    indexed: int = 0
    chunks: int = 0
    skipped_self: int = 0
    failed: int = 0
    seconds: float = 0.0
    by_type: dict = field(default_factory=dict)
    files: list = field(default_factory=list)
    error: str | None = None

    def as_dict(self) -> dict:
        return {k: getattr(self, k) for k in
                ("root", "found", "supported", "indexed", "chunks",
                 "skipped_self", "failed", "seconds", "by_type", "files",
                 "error")}


def preview(folder: str | Path) -> Scan:
    """What is in there, without reading a single document."""
    root = Path(folder).expanduser()
    s = Scan(root=str(root))
    if not root.exists():
        s.error = f"No such folder: {root}"
        return s
    if not root.is_dir():
        s.error = f"Not a folder: {root}"
        return s

    total_bytes = 0
    for p in sorted(root.rglob("*")):
        if any(part in SKIP_DIRS or part.startswith(".") for part in p.parts[len(root.parts):]):
            continue
        if not p.is_file():
            continue
        s.found += 1
        ext = p.suffix.lower()
        if ext in pipeline.SUPPORTED:
            s.supported += 1
            s.by_type[ext] = s.by_type.get(ext, 0) + 1
            total_bytes += p.stat().st_size
            if len(s.files) < MAX_FILES:
                s.files.append(str(p))
    if s.supported > MAX_FILES:
        s.error = (f"{s.supported} supported files - over the {MAX_FILES} limit. "
                   "Point at a narrower folder.")
    elif total_bytes > MAX_BYTES:
        s.error = (f"{total_bytes/1048576:.0f} MB of documents - over the "
                   f"{MAX_BYTES//1048576} MB limit for one scan.")
    return s


def ingest(folder: str | Path, client=None, progress=None) -> Scan:
    """Index everything supported under `folder`, in place."""
    s = preview(folder)
    if s.error or not s.files:
        if not s.error:
            s.error = "No supported documents found in that folder."
        return s

    t0 = time.perf_counter()
    paths = [Path(f) for f in s.files]
    for i, p in enumerate(paths, 1):
        if progress:
            progress(i, len(paths), p.name)
        try:
            stats = pipeline.build([p], client=client, verbose=False)
            if stats.get("chunks"):
                s.indexed += 1
                s.chunks += stats["chunks"]
        except pipeline.SelfGenerated:
            s.skipped_self += 1
        except Exception:
            s.failed += 1
    s.seconds = time.perf_counter() - t0
    return s
