"""
Point the workbench at a folder on this machine and index what is in it.

PS 26117 asks for "a local knowledge base connector" so the assistant can
ground itself in "the organization's own manuals, SOPs and past
correspondence". Uploading files one at a time does not describe how an
engineer actually works - the manuals already sit in a folder on the server.

Nothing leaves the machine: this reads from a local path with the same ingest
pipeline the upload button uses.

Two rules that matter more than they look:

  * The folder is walked, never copied. A 400 MB manuals directory should not
    be duplicated into data/corpus to be read once.
  * Files generated by this system are skipped, as everywhere else. A folder
    that happens to contain last week's approval notes must not turn them into
    evidence.
"""

from __future__ import annotations

import os
import time
from dataclasses import dataclass, field
from pathlib import Path

from ingest import pipeline

# Walking an entire home directory by accident should not be possible - but
# 400 turned out to be a wall a perfectly ordinary "Documents" folder hits
# (1,964 supported files on one real laptop), not just an accident guard.
# Raised to a size that covers a real folder of plant manuals; SCAN_CAP above
# is still what stops someone pointing this at their whole home directory.
MAX_FILES = 3000
MAX_BYTES = 2 * 1024 * 1024 * 1024
# A hard ceiling on how many filesystem entries one scan will even look at,
# independent of MAX_FILES - see the cycle note on preview() below for why
# this needs to be a wall during the walk, not a check after it finishes.
SCAN_CAP = 20_000
SKIP_DIRS = {".git", "node_modules", "__pycache__", ".venv", "venv",
             "Library", "System", ".Trash", "site-packages", ".cache",
             # Windows noise, and the two that matter most: "Application
             # Data" and "Local Settings" are legacy reparse points that
             # exist purely to redirect old software into AppData - walking
             # into one revisits AppData a second time under a different
             # name, and on some profiles they form an outright cycle back
             # on themselves.
             "AppData", "Application Data", "Local Settings",
             "$RECYCLE.BIN", "System Volume Information"}


@dataclass
class Scan:
    root: str
    found: int = 0
    supported: int = 0
    indexed: int = 0
    chunks: int = 0
    skipped_self: int = 0
    failed: int = 0
    seconds: float = 0.0
    by_type: dict = field(default_factory=dict)
    files: list = field(default_factory=list)
    error: str | None = None

    def as_dict(self) -> dict:
        return {k: getattr(self, k) for k in
                ("root", "found", "supported", "indexed", "chunks",
                 "skipped_self", "failed", "seconds", "by_type", "files",
                 "error")}


def preview(folder: str | Path) -> Scan:
    """What is in there, without reading a single document.

    Walks with os.walk rather than Path.rglob, and for one reason: rglob
    follows a directory-shaped reparse point wherever it points, and never
    checks whether it has been there before. A Windows profile is full of
    exactly that - "Application Data" and "Local Settings" are legacy
    junctions back into AppData, and on some profiles they form an actual
    cycle. rglob("*") on one of those does not error and does not finish; it
    was reported back as the folder picker "timing out", because from the
    browser's side that is indistinguishable from a request that never
    returns. Tracking each directory's resolved real path and refusing to
    descend into one twice closes that hole regardless of which specific
    reparse point causes it, and a hard cap on entries visited is the
    backstop for a folder that is merely enormous rather than cyclic.
    """
    root = Path(folder).expanduser()
    s = Scan(root=str(root))
    if not root.exists():
        s.error = f"No such folder: {root}"
        return s
    if not root.is_dir():
        s.error = f"Not a folder: {root}"
        return s

    total_bytes = 0
    visited_dirs: set[str] = set()
    scanned = 0
    for dirpath, dirnames, filenames in os.walk(root, topdown=True, followlinks=False):
        try:
            real = os.path.realpath(dirpath)
        except OSError:
            real = dirpath
        if real in visited_dirs:
            dirnames[:] = []
            continue
        visited_dirs.add(real)

        dirnames[:] = sorted(d for d in dirnames
                             if d not in SKIP_DIRS and not d.startswith("."))
        for fname in sorted(filenames):
            if fname.startswith("."):
                continue
            scanned += 1
            if scanned > SCAN_CAP:
                s.error = (f"More than {SCAN_CAP:,} files under this folder - "
                           "point at a narrower one.")
                return s
            p = Path(dirpath) / fname
            try:
                if not p.is_file():
                    continue
            except OSError:
                continue
            s.found += 1
            ext = p.suffix.lower()
            if ext in pipeline.SUPPORTED:
                s.supported += 1
                s.by_type[ext] = s.by_type.get(ext, 0) + 1
                try:
                    total_bytes += p.stat().st_size
                except OSError:
                    continue
                if len(s.files) < MAX_FILES:
                    s.files.append(str(p))
        if s.supported > MAX_FILES:
            s.error = (f"{s.supported} supported files - over the {MAX_FILES} limit. "
                       "Point at a narrower folder.")
            return s
        if total_bytes > MAX_BYTES:
            s.error = (f"{total_bytes/1048576:.0f} MB of documents - over the "
                       f"{MAX_BYTES//1048576} MB limit for one scan.")
            return s
    return s


def ingest(folder: str | Path, client=None, progress=None) -> Scan:
    """Index everything supported under `folder`, in place."""
    s = preview(folder)
    if s.error or not s.files:
        if not s.error:
            s.error = "No supported documents found in that folder."
        return s

    t0 = time.perf_counter()
    paths = [Path(f) for f in s.files]
    for i, p in enumerate(paths, 1):
        if progress:
            progress(i, len(paths), p.name)
        try:
            stats = pipeline.build([p], client=client, verbose=False)
            if stats.get("chunks"):
                s.indexed += 1
                s.chunks += stats["chunks"]
        except pipeline.SelfGenerated:
            s.skipped_self += 1
        except Exception:
            s.failed += 1
    s.seconds = time.perf_counter() - t0
    return s



# ---------------------------------------------------------------------------
# browsing
# ---------------------------------------------------------------------------

def places() -> list[dict]:
    """Obvious starting points, so nobody has to type a path from memory."""
    home = Path.home()
    out = []
    for label, path in [("Home", home), ("Desktop", home / "Desktop"),
                        ("Documents", home / "Documents"),
                        ("Downloads", home / "Downloads")]:
        if path.exists():
            out.append({"label": label, "path": str(path)})
    return out


def listdir(folder: str | Path) -> dict:
    """
    One level of a directory, for the picker.

    A browser file picker cannot hand back a real filesystem path - that is a
    deliberate security boundary, and it is why typing the path was the only
    option at first. But this backend runs on the same machine, so it can list
    directories directly and the picker gets real paths without uploading or
    copying anything.
    """
    root = Path(folder).expanduser()
    if not root.exists():
        return {"error": f"No such folder: {root}"}
    if not root.is_dir():
        return {"error": f"Not a folder: {root}"}

    dirs, n_supported, n_files = [], 0, 0
    try:
        for p in sorted(root.iterdir(), key=lambda x: x.name.lower()):
            if p.name.startswith("."):
                continue
            if p.is_dir():
                if p.name in SKIP_DIRS:
                    continue
                # how many readable documents sit directly inside, so the user
                # can see which branch is worth opening
                try:
                    inside = sum(1 for c in p.iterdir()
                                 if c.is_file()
                                 and c.suffix.lower() in pipeline.SUPPORTED)
                except PermissionError:
                    inside = -1
                dirs.append({"name": p.name, "path": str(p), "docs": inside})
            elif p.is_file():
                n_files += 1
                if p.suffix.lower() in pipeline.SUPPORTED:
                    n_supported += 1
    except PermissionError:
        return {"error": f"No permission to read {root}"}

    parent = str(root.parent) if root.parent != root else None
    return {"path": str(root), "parent": parent, "dirs": dirs[:200],
            "files": n_files, "supported": n_supported,
            "crumbs": [{"name": q.name or "/", "path": str(q)}
                       for q in reversed([root, *root.parents])][-6:]}



def choose() -> dict:
    """
    Open the machine's own folder chooser.

    A browser cannot open a dialog that returns a filesystem path - that is the
    security boundary that forced typing (and the in-page browser) in the
    first place. This backend is a local process though, so it can ask the OS
    directly and hand back a real path - one native dialog per platform, in
    the toolkit that ships with that OS rather than one this project would
    have to bundle.
    """
    import sys

    if sys.platform == "darwin":
        return _choose_macos()
    if sys.platform == "win32":
        return _choose_windows()
    return _choose_linux()


def _choose_macos() -> dict:
    import subprocess
    script = ('POSIX path of (choose folder with prompt '
              '"Choose a folder for the Sovereign Workbench to read")')
    try:
        r = subprocess.run(["osascript", "-e", script],
                           capture_output=True, text=True, timeout=180)
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return {"error": "The chooser timed out."}
    if r.returncode != 0:
        err = r.stderr or ""
        # Cancelling is the ordinary path, not an error. macOS reports it as
        # "User cancelled. (-128)" - with two l's. This code looked for the
        # American spelling, never matched, and fell into the error branch, so
        # pressing Cancel opened the fallback path box instead of doing
        # nothing. Match the error NUMBER, which does not vary by locale or
        # spelling, and keep both spellings as a belt.
        if "-128" in err or "cancel" in err.lower():
            return {"cancelled": True}
        return {"error": err.strip()[:160] or "Could not open the chooser"}
    return {"path": r.stdout.strip().rstrip("/")}


def _choose_windows() -> dict:
    # WinForms' FolderBrowserDialog, driven from PowerShell so nothing needs
    # bundling - every Windows box already has both. It needs an STA thread;
    # classic powershell.exe (not pwsh/PowerShell 7) is STA by default, which
    # is the whole reason this targets "powershell" specifically.
    import subprocess
    script = (
        "Add-Type -AssemblyName System.Windows.Forms | Out-Null;"
        "$f = New-Object System.Windows.Forms.FolderBrowserDialog;"
        "$f.Description = 'Choose a folder for the Sovereign Workbench to read';"
        "$f.ShowNewFolderButton = $false;"
        "if ($f.ShowDialog() -eq [System.Windows.Forms.DialogResult]::OK) {"
        "  Write-Output $f.SelectedPath"
        "}"
    )
    try:
        r = subprocess.run(
            ["powershell", "-NoProfile", "-NonInteractive", "-Command", script],
            capture_output=True, text=True, timeout=180)
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return {"error": "Native chooser is unavailable - browse instead."}
    if r.returncode != 0:
        return {"error": (r.stderr or "").strip()[:160]
                or "Could not open the chooser"}
    path = r.stdout.strip()
    # No SelectedPath printed means Cancel, not an error - ShowDialog()
    # returned anything other than OK.
    return {"path": path} if path else {"cancelled": True}


def _choose_linux() -> dict:
    # No single toolkit ships with every distro. Try the two that cover
    # GNOME and KDE; if neither binary exists, fall back honestly instead of
    # guessing at a third.
    import shutil
    import subprocess

    for binary, args in (
        ("zenity", ["--file-selection", "--directory",
                    "--title=Choose a folder for the Sovereign Workbench to read"]),
        ("kdialog", ["--getexistingdirectory", str(Path.home())]),
    ):
        if not shutil.which(binary):
            continue
        try:
            r = subprocess.run([binary, *args], capture_output=True,
                               text=True, timeout=180)
        except subprocess.TimeoutExpired:
            return {"error": "The chooser timed out."}
        if r.returncode != 0:
            return {"cancelled": True}      # both tools exit non-zero on Cancel
        path = r.stdout.strip()
        return {"path": path} if path else {"cancelled": True}
    return {"error": "No folder chooser found (zenity/kdialog) - browse instead."}
