"""
Point the workbench at a folder on this machine and index what is in it.

PS 26117 asks for "a local knowledge base connector" so the assistant can
ground itself in "the organization's own manuals, SOPs and past
correspondence". Uploading files one at a time does not describe how an
engineer actually works - the manuals already sit in a folder on the server.

Nothing leaves the machine: this reads from a local path with the same ingest
pipeline the upload button uses.

Two rules that matter more than they look:

  * The folder is walked, never copied. A 400 MB manuals directory should not
    be duplicated into data/corpus to be read once.
  * Files generated by this system are skipped, as everywhere else. A folder
    that happens to contain last week's approval notes must not turn them into
    evidence.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from pathlib import Path

from ingest import pipeline

# Walking an entire home directory by accident should not be possible.
MAX_FILES = 400
MAX_BYTES = 300 * 1024 * 1024
SKIP_DIRS = {".git", "node_modules", "__pycache__", ".venv", "venv",
             "Library", "System", ".Trash", "site-packages", ".cache"}


@dataclass
class Scan:
    root: str
    found: int = 0
    supported: int = 0
    indexed: int = 0
    chunks: int = 0
    skipped_self: int = 0
    failed: int = 0
    seconds: float = 0.0
    by_type: dict = field(default_factory=dict)
    files: list = field(default_factory=list)
    error: str | None = None

    def as_dict(self) -> dict:
        return {k: getattr(self, k) for k in
                ("root", "found", "supported", "indexed", "chunks",
                 "skipped_self", "failed", "seconds", "by_type", "files",
                 "error")}


def preview(folder: str | Path) -> Scan:
    """What is in there, without reading a single document."""
    root = Path(folder).expanduser()
    s = Scan(root=str(root))
    if not root.exists():
        s.error = f"No such folder: {root}"
        return s
    if not root.is_dir():
        s.error = f"Not a folder: {root}"
        return s

    total_bytes = 0
    for p in sorted(root.rglob("*")):
        if any(part in SKIP_DIRS or part.startswith(".") for part in p.parts[len(root.parts):]):
            continue
        if not p.is_file():
            continue
        s.found += 1
        ext = p.suffix.lower()
        if ext in pipeline.SUPPORTED:
            s.supported += 1
            s.by_type[ext] = s.by_type.get(ext, 0) + 1
            total_bytes += p.stat().st_size
            if len(s.files) < MAX_FILES:
                s.files.append(str(p))
    if s.supported > MAX_FILES:
        s.error = (f"{s.supported} supported files - over the {MAX_FILES} limit. "
                   "Point at a narrower folder.")
    elif total_bytes > MAX_BYTES:
        s.error = (f"{total_bytes/1048576:.0f} MB of documents - over the "
                   f"{MAX_BYTES//1048576} MB limit for one scan.")
    return s


def ingest(folder: str | Path, client=None, progress=None) -> Scan:
    """Index everything supported under `folder`, in place."""
    s = preview(folder)
    if s.error or not s.files:
        if not s.error:
            s.error = "No supported documents found in that folder."
        return s

    t0 = time.perf_counter()
    paths = [Path(f) for f in s.files]
    for i, p in enumerate(paths, 1):
        if progress:
            progress(i, len(paths), p.name)
        try:
            stats = pipeline.build([p], client=client, verbose=False)
            if stats.get("chunks"):
                s.indexed += 1
                s.chunks += stats["chunks"]
        except pipeline.SelfGenerated:
            s.skipped_self += 1
        except Exception:
            s.failed += 1
    s.seconds = time.perf_counter() - t0
    return s



# ---------------------------------------------------------------------------
# browsing
# ---------------------------------------------------------------------------

def places() -> list[dict]:
    """Obvious starting points, so nobody has to type a path from memory."""
    home = Path.home()
    out = []
    for label, path in [("Home", home), ("Desktop", home / "Desktop"),
                        ("Documents", home / "Documents"),
                        ("Downloads", home / "Downloads")]:
        if path.exists():
            out.append({"label": label, "path": str(path)})
    return out


def listdir(folder: str | Path) -> dict:
    """
    One level of a directory, for the picker.

    A browser file picker cannot hand back a real filesystem path - that is a
    deliberate security boundary, and it is why typing the path was the only
    option at first. But this backend runs on the same machine, so it can list
    directories directly and the picker gets real paths without uploading or
    copying anything.
    """
    root = Path(folder).expanduser()
    if not root.exists():
        return {"error": f"No such folder: {root}"}
    if not root.is_dir():
        return {"error": f"Not a folder: {root}"}

    dirs, n_supported, n_files = [], 0, 0
    try:
        for p in sorted(root.iterdir(), key=lambda x: x.name.lower()):
            if p.name.startswith("."):
                continue
            if p.is_dir():
                if p.name in SKIP_DIRS:
                    continue
                # how many readable documents sit directly inside, so the user
                # can see which branch is worth opening
                try:
                    inside = sum(1 for c in p.iterdir()
                                 if c.is_file()
                                 and c.suffix.lower() in pipeline.SUPPORTED)
                except PermissionError:
                    inside = -1
                dirs.append({"name": p.name, "path": str(p), "docs": inside})
            elif p.is_file():
                n_files += 1
                if p.suffix.lower() in pipeline.SUPPORTED:
                    n_supported += 1
    except PermissionError:
        return {"error": f"No permission to read {root}"}

    parent = str(root.parent) if root.parent != root else None
    return {"path": str(root), "parent": parent, "dirs": dirs[:200],
            "files": n_files, "supported": n_supported,
            "crumbs": [{"name": q.name or "/", "path": str(q)}
                       for q in reversed([root, *root.parents])][-6:]}



def choose() -> dict:
    """
    Open the machine's own folder chooser.

    A browser cannot open a dialog that returns a filesystem path - that is the
    security boundary that forced typing in the first place. This backend is a
    local process though, so it can ask the OS directly and hand back a real
    path. On anything other than macOS this simply reports that the picker is
    unavailable and the typed path still works.
    """
    import subprocess
    import sys

    if sys.platform != "darwin":
        return {"error": "Native chooser is macOS only - type or browse instead."}
    script = ('POSIX path of (choose folder with prompt '
              '"Choose a folder for the Sovereign Workbench to read")')
    try:
        r = subprocess.run(["osascript", "-e", script],
                           capture_output=True, text=True, timeout=180)
    except subprocess.TimeoutExpired:
        return {"error": "The chooser timed out."}
    if r.returncode != 0:
        err = r.stderr or ""
        # Cancelling is the ordinary path, not an error. macOS reports it as
        # "User cancelled. (-128)" - with two l's. This code looked for the
        # American spelling, never matched, and fell into the error branch, so
        # pressing Cancel opened the fallback path box instead of doing
        # nothing. Match the error NUMBER, which does not vary by locale or
        # spelling, and keep both spellings as a belt.
        if "-128" in err or "cancel" in err.lower():
            return {"cancelled": True}
        return {"error": err.strip()[:160] or "Could not open the chooser"}
    return {"path": r.stdout.strip().rstrip("/")}
