"""
Analyse a folder the moment it is chosen.

Picking a folder and then having to ask "so what is in it" is a wasted step -
the answer is the same every time and the system can work it out itself. This
runs on selection: count the files, group them by type, index them, and have
the reasoning lane say what the folder actually contains.

It streams the same event shapes as agents/workbench.py, so the UI renders it
with the activity panel it already has.
"""

from __future__ import annotations

import collections
import time
from pathlib import Path
from typing import Iterator

from core.llm import Client
from tools import folder as folder_tool

# A folder summary is a survey, not an answer to a question, so it draws on
# more of the corpus than a normal query would.
SURVEY_K = 8

SUMMARY_SYS = (
    "You are describing what a folder of plant documents contains, for an "
    "engineer who has just pointed you at it.\n"
    "Rules:\n"
    "1. Say what KIND of documents these are and what equipment they cover.\n"
    "2. Name the equipment tags you can see. Tags are the join key an engineer "
    "will use next.\n"
    "3. Call out anything that looks like a deviation, non-conformance or open "
    "action, with its citation.\n"
    "4. Use only the passages given. Do not estimate or assume a number.\n"
    "5. Six lines at most. No preamble - start with what the folder holds.\n"
    "6. English."
)


def analyse(path: str | Path, client: Client | None = None,
            index: bool = True) -> Iterator[dict]:
    """Survey a folder end to end, yielding UI events as it goes."""
    client = client or Client()
    t0 = time.perf_counter()
    root = Path(path).expanduser()

    # 1 -- count -----------------------------------------------------------
    yield {"type": "step", "id": "scan", "status": "running",
           "label": "Looking in the folder"}
    scan = folder_tool.preview(root)
    if scan.error:
        yield {"type": "step", "id": "scan", "status": "fail",
               "label": "Looking in the folder", "detail": scan.error[:80]}
        yield {"type": "error", "message": scan.error}
        return

    kinds = collections.Counter(scan.by_type)
    yield {"type": "step", "id": "scan", "status": "done",
           "label": "Looking in the folder",
           "detail": f"{scan.found} files, {scan.supported} readable"}
    yield {"type": "folder_scan", "root": str(root), "found": scan.found,
           "supported": scan.supported, "by_type": dict(kinds),
           "files": [Path(f).name for f in scan.files[:40]]}

    if not scan.supported:
        yield {"type": "done", "answer": "", "total_s": round(time.perf_counter() - t0, 1),
               "empty": True}
        return

    # 2 -- read ------------------------------------------------------------
    chunks = 0
    if index:
        yield {"type": "step", "id": "read", "status": "running",
               "label": f"Reading {scan.supported} file(s)"}
        res = folder_tool.ingest(root, client=client)
        chunks = res.chunks
        detail = (f"{res.indexed} new, {res.chunks} passages"
                  if res.indexed else
                  f"{scan.supported} already indexed - nothing changed")
        if res.skipped_self:
            detail += f" · skipped {res.skipped_self} generated by this system"
        yield {"type": "step", "id": "read", "status": "done",
               "label": f"Reading {scan.supported} file(s)", "detail": detail}

    # 3 -- what is in it ---------------------------------------------------
    yield {"type": "step", "id": "survey", "status": "running",
           "label": "Working out what it holds"}
    from ingest.pipeline import context
    # Ask about the folder's subject matter rather than a specific fact, and
    # spread the passages across files so one document cannot dominate.
    ctx, hits = context(
        "equipment tags inspection findings deviations specifications readings",
        SURVEY_K, client=client, per_source=2, min_score=0.0)

    listing = "\n".join(f"  - {Path(f).name}" for f in scan.files[:25])
    prompt = (f"FOLDER: {root}\n"
              f"{scan.found} files, {scan.supported} readable.\n"
              f"By type: {', '.join(f'{v} {k}' for k, v in kinds.most_common())}\n"
              f"Files:\n{listing}\n\n"
              f"PASSAGES FROM THOSE FILES:\n{ctx}\n\n"
              "Describe what this folder contains.")

    answer = ""
    reply = None
    for ev in client.stream("reason", prompt, system=SUMMARY_SYS):
        if ev["type"] == "token":
            answer += ev["text"]
            yield {"type": "token", "text": ev["text"]}
        elif ev["type"] == "done":
            reply = ev["reply"]

    yield {"type": "step", "id": "survey", "status": "done",
           "label": "Working out what it holds",
           "detail": f"{len(hits)} passages across "
                     f"{len({h.chunk.source for h in hits})} file(s)"}
    yield {"type": "sources",
           "retrieval_s": 0, "searched": True, "grounded": bool(ctx),
           "items": [{"n": i, "cite": h.chunk.cite(), "source": h.chunk.source,
                      "page": h.chunk.page, "heading": h.chunk.heading,
                      "kind": h.chunk.kind, "score": round(h.score, 3),
                      "text": h.chunk.text}
                     for i, h in enumerate(hits, 1)]}
    yield {"type": "done", "answer": answer,
           "model": reply.model if reply else "",
           "chunks": chunks, "files": scan.supported,
           "total_s": round(time.perf_counter() - t0, 1),
           "tok_per_s": round(reply.tok_per_s, 1) if reply else 0,
           "grounded": bool(ctx)}
